spring.application.name=Apache camel

camel.springboot.main-run-controller=true

diretorioEntrada=C:/Users/pedro/Downloads/entrada apache camel
diretorioSaida=C:/Users/pedro/Downloads/saida apache camel