spring.application.name=Apache camel

camel.springboot.main-run-controller=true

diretorioEntrada=C:/Users/pedro/Downloads/entrada apache camel
diretorioSaida=C:/Users/pedro/Downloads/saida apache camel

xpathCnpjTransportadora = //ns:transp/ns:transporta/ns:CNPJ/text()
xpathTransportadora2 = //ns:transp/ns:transporta/ns:CNPJ/[text()='2']
xpathPedido = //ns:infAdic/ns:obsCont[@xCampo='PEDIDO1']/ns:xTexto/text()

UrlApiTransportadora2 = http://0.0.0.0:8080